[project]
name = "mitmproxy-rs-demo"
version = "0.1.0"
description = "Demo script for mitmproxy_rs local redirector"
requires-python = ">=3.8"

[project.scripts]
demo = "demo:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"